import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";
import Sidebar from "../components/layout/Sidebar";
import PageWrapper from "@/components/layout/PageWrapper";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Arsenal } from "next/font/google";
import Head from "next/head";

const arsenal = Arsenal({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-arsenal",
});

export const metadata: Metadata = {
  title: "LensPR dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={arsenal.variable}>
          <SignedIn>
            <PageWrapper>
              <ThemeProvider>
                <div className="flex">
                  {/* Sidebar fijo (usa su propio tamaño animado) */}
                  <Sidebar />
                  {/* Contenedor principal sin margen adicional (PageWrapper ya aplica padding a la izquierda) */}
                  <div className="flex-1 min-h-screen pt-2 px-6 transition-all duration-300 bg-white">
                    {/* User Profile Button en la barra superior */}
                    <div className="flex justify-end mb-4"></div>
                    <Head>
                      <link rel="icon" href="/favicon.ico" />
                    </Head>
                    {children}
                  </div>
                </div>
              </ThemeProvider>
            </PageWrapper>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}