import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";
import Sidebar from "../components/layout/Sidebar";
import PageWrapper from "@/components/layout/PageWrapper";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Arsenal } from "next/font/google";
import Head from "next/head";

const arsenal = Arsenal({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-arsenal",
});

export const metadata: Metadata = {
  title: "LensPR dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={arsenal.variable}>
          <SignedIn>
            <PageWrapper>
              <ThemeProvider>
                <div className="flex">
                  {/* Sidebar con width fijo */}
                  <div className="fixed left-0 top-0 h-screen w-[150px] bg-gray-900 text-black z-50">
                    <Sidebar />
                  </div>
                  {/* Contenedor principal con padding izquierdo en lugar de margen */}
                  <div className="flex-1 min-h-screen pt-2 px-6 transition-all duration-300 lg:ml-[150px] bg-white">
                    {/* User Profile Button en la barra superior */}
                    <div className="flex justify-end mb-4"></div>
                    <Head>
                      <link rel="icon" href="/favicon.ico" />
                    </Head>
                    {children}
                  </div>
                </div>
              </ThemeProvider>
            </PageWrapper>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
